
joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'
  publish_rate: 50.0
  cmd_vel_timeout: 0.25
  enable_odom_tf: true
  base_frame_id: base_footprint
  pose_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

  linear:
    x:
      has_velocity_limits    : false
      max_velocity           : 1.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.1   # m/s^2
  angular:
    z:
      has_velocity_limits    : false
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 5.0   # rad/s^2
